const { contextBridge, ipcRenderer } = require('electron');

// 所有 on* 订阅统一经此注册，并回传退订函数：渲染层若重新初始化，
// 不退订就会叠加监听器，同一条通知被回调多次。
function subscribe(channel, handler) {
  ipcRenderer.on(channel, handler);
  return () => ipcRenderer.removeListener(channel, handler);
}

contextBridge.exposeInMainWorld('notchAPI', {
  launcherLayout: mode => ipcRenderer.invoke('launcher:layout', mode),
  launcherPosition: position => ipcRenderer.invoke('launcher:position', position),
  assistantGenerate: input => ipcRenderer.invoke('assistant:generate',input),
  assistantCancel: () => ipcRenderer.invoke('assistant:cancel'),
  desktopAction: input => ipcRenderer.invoke('desktop:action',input),
  onDesktopProgress: callback => {const fn=(_event,p)=>callback(p);ipcRenderer.on('desktop:progress',fn);return ()=>ipcRenderer.removeListener('desktop:progress',fn);},
  onLauncherOpen: cb => subscribe('launcher:open', (_e,payload) => cb(payload)),
  onLauncherChanged: cb => subscribe('launcher:changed', (_e,payload) => cb(payload)),
  mailGet: () => ipcRenderer.invoke('mail:get'),
  mailSave: p => ipcRenderer.invoke('mail:save', p),
  mailRefresh: p => ipcRenderer.invoke('mail:refresh', p),
  mailRead: p => ipcRenderer.invoke('mail:read', p),
  mailRemove: p => ipcRenderer.invoke('mail:remove', p),
  mailOpen: p => ipcRenderer.invoke('mail:open', p),
  mailCancel: () => ipcRenderer.invoke('mail:cancel'),
  packsGet:()=>ipcRenderer.invoke('packs:get'),
  packsCommand:p=>ipcRenderer.invoke('packs:command',p),
  packsSelect:id=>ipcRenderer.invoke('packs:select',id),
  packsImport:()=>ipcRenderer.invoke('packs:import'),
  packsOpen:id=>ipcRenderer.invoke('packs:open',id),
  packsCompose:p=>ipcRenderer.invoke('packs:compose',p),
  packsCopy:p=>ipcRenderer.invoke('packs:copy',p),
  packsGenerate:p=>ipcRenderer.invoke('packs:generate',p),
  packsCancel:()=>ipcRenderer.invoke('packs:cancel'),
  packsConfig:()=>ipcRenderer.invoke('packs:config'),
  onPacksSelect:cb=>subscribe('packs:select',(_e,id)=>cb(id)),
  onPacksChanged:cb=>subscribe('packs:changed',()=>cb()),
  openQuickClipboard: () => ipcRenderer.invoke('quick-clip:open'),
  quickClipboard: input => ipcRenderer.invoke('quick-clip:request',input),
  onQuickClipRequest: cb => subscribe('quick-clip:host-request',(_e,value)=>cb(value)),
  quickClipResult: (requestId,result) => ipcRenderer.send('quick-clip:host-result',{requestId,result}),
  quickClipChanged: () => ipcRenderer.send('quick-clip:changed'),
  onQuickClipChanged: cb => subscribe('quick-clip:changed',()=>cb()),
  panelPosition: (action) => ipcRenderer.invoke('panel:position', action),
  panelDrag: (phase,payload) => ipcRenderer.invoke('panel:drag',phase,payload),
  onPanelPlacement: (cb) => subscribe('panel:placement',(_e,value)=>cb(value)),
  openFloat: (payload) => ipcRenderer.invoke('floats:open', payload),
  detachDrag: (phase, payload) => ipcRenderer.invoke('floats:detach-drag', phase, payload),
  onDetachCancelled: (cb) => subscribe('floats:detach-cancelled', () => cb()),
  dockFloat: (key) => ipcRenderer.invoke('floats:dock', key),
  onFloatList: (cb) => subscribe('floats:list', (_event, keys) => cb(keys)),
  onFloatRequest: (cb) => subscribe('floats:host-request', (_event, payload) => cb(payload)),
  floatResult: (requestId, result) => ipcRenderer.send('floats:host-result', { requestId, result }),
  broadcastFloat: (payload) => ipcRenderer.send('floats:broadcast', payload),
  prepareMeeting: (text) => ipcRenderer.invoke('meeting:prepare', text),
  cancelMeetingPrep: () => ipcRenderer.invoke('meeting:cancel'),
  importMeetingFiles: () => ipcRenderer.invoke('meeting:import'),
  copyMeetingText: (text) => ipcRenderer.invoke('meeting:copy', text),
  setMode: (mode) => ipcRenderer.invoke('window:set-mode', mode),
  beginCollapse: () => ipcRenderer.invoke('window:begin-collapse'),
  setTab: (tab) => ipcRenderer.invoke('window:set-tab', tab),
  ensureCamera: () => ipcRenderer.invoke('media:camera'),
  ensureMicrophone: () => ipcRenderer.invoke('media:microphone'),
  openExternal: (url) => ipcRenderer.invoke('shell:openExternal', url),
  openPath: (p) => ipcRenderer.invoke('shell:openPath', p),
  openPrivacySettings: (pane) => ipcRenderer.invoke('shell:open-privacy-settings', pane),
  getPermissionStatuses: () => ipcRenderer.invoke('permissions:get-status'),
  requestPermission: kind => ipcRenderer.invoke('permissions:request', kind),
  revealCurrentApp: () => ipcRenderer.invoke('app:reveal-current'),
  relaunchApp: () => ipcRenderer.invoke('app:relaunch'),
  getMusicStatus: () => ipcRenderer.invoke('music:status'),
  controlMusic: (action) => ipcRenderer.invoke('music:control', action),
  inspectLink: (url) => ipcRenderer.invoke('links:inspect', url),
  linkSettings: changes=>ipcRenderer.invoke('links:settings',changes),
  linkImage: ref=>ipcRenderer.invoke('links:image',ref),
  linkAI: input=>ipcRenderer.invoke('links:ai',input),
  linkCancel: ()=>ipcRenderer.invoke('links:cancel'),
  listWindows: () => ipcRenderer.invoke('windows:list'),
  windowGroupsGet:()=>ipcRenderer.invoke('window-groups:get'),
  windowGroupsCommand:c=>ipcRenderer.invoke('window-groups:command',c),
  toolGroupsGet: () => ipcRenderer.invoke('window-tools:get'),
  toolGroupsCommand: (command) => ipcRenderer.invoke('window-tools:command', command),
  focusWindow: (windowId) => ipcRenderer.invoke('windows:focus', windowId),
  saveRecording: (payload) => ipcRenderer.invoke('recordings:save', payload),
  startTimedRecording: (payload) => ipcRenderer.invoke('recordings:timed-start', payload),
  cancelTimedRecording: (requestId) => ipcRenderer.invoke('recordings:timed-cancel', requestId),
  recoverRecordings: () => ipcRenderer.invoke('recordings:recover'),
  plannerGet:()=>ipcRenderer.invoke('planner:get'),
  plannerLegacy:()=>ipcRenderer.invoke('planner:legacy'),
  plannerCommand:c=>ipcRenderer.invoke('planner:command',c),
  plannerSuggest:input=>ipcRenderer.invoke('planner:suggest',input),
  plannerCancel:()=>ipcRenderer.invoke('planner:cancel'),
  plannerVoice:action=>ipcRenderer.invoke('planner:voice',action),
  onPlannerOpen:cb=>ipcRenderer.on('planner:open',()=>cb()),
  organizeVoice: (payload) => ipcRenderer.invoke('voice:organize', payload),
  cancelVoice: (id) => ipcRenderer.invoke('voice:cancel', id),
  readRecording: (audioPath) => ipcRenderer.invoke('recordings:read', audioPath),
  deleteRecording: (audioPath) => ipcRenderer.invoke('recordings:delete', audioPath),
  revealRecording: (audioPath) => ipcRenderer.invoke('recordings:reveal', audioPath),
  organizeMaterial: (payload) => ipcRenderer.invoke('smart:organize-material', payload),
  aiCreateProposal: (input) => ipcRenderer.invoke('ai:create-proposal', input),
  aiCancelRun: (runId) => ipcRenderer.invoke('ai:cancel-run', { runId }),
  aiGetRun: (runId) => ipcRenderer.invoke('ai:get-run', { runId }),
  aiListRuns: (limit) => ipcRenderer.invoke('ai:list-runs', { limit }),
  aiConfirmProposal: (runId, proposal, confirmed) => ipcRenderer.invoke('ai:confirm-proposal', {
    runId,
    proposal,
    confirmed: confirmed === true,
  }),
  onAiRunChanged: (cb) => subscribe('ai:run-changed', (event, run) => cb(run)),
  onAiToolRequest: (cb) => subscribe('ai:tool-request', (event, request) => cb(request)),
  completeAiToolRequest: (requestId, result) => ipcRenderer.send('ai:tool-result', { requestId, result }),
  openCredential:id=>ipcRenderer.invoke('credentials:open',id),
  referenceGet:()=>ipcRenderer.invoke('reference:get'),
  referenceImage:id=>ipcRenderer.invoke('reference:image',id),
  referenceChoose:()=>ipcRenderer.invoke('reference:choose'),
  referenceImport:data=>ipcRenderer.invoke('reference:import',data),
  listCredentials: () => ipcRenderer.invoke('credentials:list'),
  getCredential: (id) => ipcRenderer.invoke('credentials:get', id),
  saveCredential: (payload) => ipcRenderer.invoke('credentials:save', payload),
  deleteCredentials: (ids) => ipcRenderer.invoke('credentials:delete-many', ids),
  copyCredential: (id, field) => ipcRenderer.invoke('credentials:copy', { id, field }),
  getTranscriptionConfig: () => ipcRenderer.invoke('transcription:get-config'),
  setTranscriptionConfig: (config) => ipcRenderer.invoke('transcription:set-config', config),
  startTranscription: () => ipcRenderer.invoke('transcription:start'),
  sendTranscriptionAudio: (bytes) => ipcRenderer.send('transcription:audio', bytes),
  finishTranscription: () => ipcRenderer.invoke('transcription:finish'),
  onTranscriptionEvent: (cb) => subscribe('transcription:event', (event, payload) => cb(payload)),
  listTaskCompletions: () => ipcRenderer.invoke('tasks:recent'),
  scheduleTodoReminders: (items) => ipcRenderer.invoke('todos:schedule-reminders', items),
  notifyPomodoro: (minutes) => ipcRenderer.invoke('pomodoro:notify', minutes),
  timerGet:()=>ipcRenderer.invoke('timer:get'),
  timerCommand:c=>ipcRenderer.invoke('timer:command',c),
  timerStartPlan:id=>ipcRenderer.invoke('timer:plan',id),
  onTodoReminder: (cb) => subscribe('todo:reminded', (event, payload) => cb(payload)),
  onEscape: (cb) => subscribe('key:escape', () => cb()),
  onToggleShortcut: (cb) => subscribe('shortcut:toggle-panel', () => cb()),
  getAppSettings: () => ipcRenderer.invoke('settings:get'),
  setFeature: (featureId, enabled) => ipcRenderer.invoke('settings:set-feature', { featureId, enabled }),
  setAutoLaunch: (enabled) => ipcRenderer.invoke('settings:set-auto-launch', enabled === true),
  setPanelShortcut: (accelerator) => ipcRenderer.invoke('settings:set-shortcut', accelerator),
  beginPanelShortcutTest: (accelerator) => ipcRenderer.invoke('settings:begin-shortcut-test', accelerator),
  confirmPanelShortcutTest: (accelerator) => ipcRenderer.invoke('settings:confirm-shortcut-test', accelerator),
  cancelPanelShortcutTest: () => ipcRenderer.invoke('settings:cancel-shortcut-test'),
  onPanelShortcutTestTriggered: (cb) => subscribe('shortcut:test-triggered', (event, payload) => cb(payload)),
  onPanelShortcutTestEnded: (cb) => subscribe('shortcut:test-ended', (event, payload) => cb(payload)),
  onAppSettingsChanged: (cb) => subscribe('settings:changed', (event, settings) => cb(settings)),
  onRecordShortcut: (cb) => subscribe('app:record-shortcut', () => cb()),
  getWorkspace: () => ipcRenderer.invoke('workspace:get'),
  loadWorkspaceData: () => ipcRenderer.invoke('workspace:load-data'),
  saveWorkspaceData: (storage) => ipcRenderer.invoke('workspace:save-data', storage),
  openWorkspace: () => ipcRenderer.invoke('workspace:open'),
  chooseWorkspace: () => ipcRenderer.invoke('workspace:choose'),
  onWorkspaceChanged: (cb) => subscribe('workspace:changed', (event, info) => cb(info)),
  onCollapseRequest: (cb) => subscribe('window:request-collapse', () => cb()),
  getMetrics: () => ipcRenderer.invoke('window:metrics'),
  onMetricsChanged: (cb) =>
    subscribe('window:metrics-changed', (event, metrics) => cb(metrics)),
  writeClipboard: (entry) => ipcRenderer.invoke('clipboard:write', entry),
  pasteClipboard: (entry) => ipcRenderer.invoke('clipboard:paste', entry),
  readClipImage: (imagePath) => ipcRenderer.invoke('clipboard:readImage', imagePath),
  normalizeClipHistory: (entries) => ipcRenderer.invoke('clipboard:normalize-history', entries),
  deleteClipImages: (paths) => ipcRenderer.invoke('clipboard:deleteImages', paths),
  onNewClipEntry: (cb) => subscribe('clipboard:new-entry', (evt, entry) => cb(entry)),
  onOpenClip: (cb) => subscribe('app:open-clip', () => cb()),
  onOpenApiSettings: (cb) => subscribe('app:open-api-settings', () => cb()),
  getMirrorGallery: () => ipcRenderer.invoke('mirror:get-gallery'),
  getMirrorImage: (imageId) => ipcRenderer.invoke('mirror:get-image', imageId),
  addMirrorImages: () => ipcRenderer.invoke('mirror:add-images'),
  replaceMirrorImage: (imageId) => ipcRenderer.invoke('mirror:replace-image', imageId),
  selectMirrorImage: (imageId) => ipcRenderer.invoke('mirror:select-image', imageId),
  removeMirrorImage: (imageId) => ipcRenderer.invoke('mirror:remove-image', imageId),
  onMirrorGalleryChanged: (cb) => subscribe('mirror:gallery-changed', (event, gallery) => cb(gallery)),
  onTaskNotification: (cb) =>
    subscribe('task-notification:show', (event, notification) => cb(notification)),
  onTaskNotificationQueue: (cb) =>
    subscribe('task-notification:queue', (event, count) => cb(count)),
  onTaskNotificationHide: (cb) =>
    subscribe('task-notification:hide', (event, eventId) => cb(eventId)),
  onTaskCompletion: (cb) =>
    subscribe('task-completion:new', (event, notification) => cb(notification)),
  taskNotificationDismissed: (eventId) =>
    ipcRenderer.send('task-notification:dismissed', eventId),
  activateTaskNotification: (eventId) =>
    ipcRenderer.invoke('task-notification:activate', eventId),
  taskNotificationHover: (paused) =>
    ipcRenderer.send('task-notification:hover', paused === true),
});
